// https://leetcode.com/problems/find-the-difference/description/?envType=problem-list-v2&envId=wn864o4j
// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.


// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

import java.util.ArrayList;
import java.util.List;
// Almost tried by myself and got it right
public class FindDiff{
    public char findTheDifference(String s, String t) {
        List<Character> list = new ArrayList<>();
        for(char c : t.toCharArray()){
            list.add(c);
        }
        for(int i = 0; i < s.length(); i++){
            if(list.contains(s.charAt(i))){
                list.remove((Character)s.charAt(i));
            }
        }
        return list.get(0);
    }
}

// public char findTheDifference(String s, String t) {
//         HashMap<Character, Integer> map = new HashMap<>();

//         for(char c : s.toCharArray()){
//             map.put(c, map.getOrDefault(c, 0) + 1);
//         }

//         for(char c : t.toCharArray()){
//             if(!map.containsKey(c) || map.get(c) == 0){
//                 return c;
//             }
//             map.put(c, map.get(c) - 1);
//         }

//         return ' '; // theoretically unreachable
//     }